sudo : required
services :
  - docker

befor_install :
  - docker build -t y0mna/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true y0mna/docker-react npm run test

language: generic 
